### ISSUE TITLE
Page jumping

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/website#145]
Currently, when you click a hash link, the page instantly jumps to the hash location.  This css would make it smoothly scroll, making for a nice feel:

```css
:root {
 scroll-behavior: smooth;
}
```
